# -*- makefile -*-

############################
###### Firmware types ######
############################

FIRMWARE_TYPE=@FIRMWARE_TYPE@

# Note: the default in contiki-ng is the nonstoring Orchestra rule,
# but with RPL lite routing (non-storing mode).
# We use RPL classic, for which the storing mode is the default.
# The non-storing rule can also be used with the RPL storing mode!

# sender based, storing Orchestra + RPL
FIRMWARE_TYPE_ORCHESTRA_SB=1
# receiver based, storing Orchestra + RPL
FIRMWARE_TYPE_ORCHESTRA_RB_S=2
# receiver based, nonstoring Orchestra, nonstoring RPL
FIRMWARE_TYPE_ORCHESTRA_RB_NS=3
# receiver based, nonstoring Orchestra, storing RPL
FIRMWARE_TYPE_ORCHESTRA_RB_NS_SR=4
# needs storing routing
FIRMWARE_TYPE_LINK=5
# needs storing routing
FIRMWARE_TYPE_MSF=6
# needs storing routing
FIRMWARE_TYPE_EMSF=7
# needs storing routing
FIRMWARE_TYPE_ALICE=8
# needs storing routing
FIRMWARE_TYPE_ALICE_RX_MULTICHANNEL=9

ifndef FIRMWARE_TYPE
  FIRMWARE_TYPE := $(FIRMWARE_TYPE_ORCHESTRA_SB)
endif

ifeq ($(FIRMWARE_TYPE),$(FIRMWARE_TYPE_ORCHESTRA_RB_NS))
  # turn OFF the storing mode
  CFLAGS += -DRPL_CONF_MOP=RPL_MOP_NON_STORING
else
  # by default, turn ON the storing mode
  CFLAGS += -DRPL_CONF_MOP=RPL_MOP_STORING_NO_MULTICAST
endif

CFLAGS += -DFIRMWARE_TYPE=$(FIRMWARE_TYPE)

CFLAGS += -DORCHESTRA_CONF_UNICAST_PERIOD=@ORCHESTRA_CONF_UNICAST_PERIOD@
CFLAGS += -DSEND_INTERVAL_SEC=@SEND_INTERVAL_SEC@
CFLAGS += -DORCHESTRA_CONF_ROOT_RULE=@ORCHESTRA_CONF_ROOT_RULE@

############################
####### Other config #######
############################

CONTIKI=../../../../../../../../..

MAKE_MAC = MAKE_MAC_TSCH
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

# Orchestra or ALICE?
ifeq ($(FIRMWARE_TYPE),$(FIRMWARE_TYPE_ALICE))
MODULES += os/services/alice
else
ifeq ($(FIRMWARE_TYPE),$(FIRMWARE_TYPE_ALICE_RX_MULTICHANNEL))
MODULES += os/services/alice
else
MODULES += os/services/orchestra
endif
endif

# enable energest (for tests only, not for simulations)
MODULES += os/services/simple-energest

CONTIKI_PROJECT = node
all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
