# -*- makefile -*-

############################
###### Firmware types ######
############################

FIRMWARE_TYPE=@FIRMWARE_TYPE@

# Note: the default in contiki-ng is the nonstoring Orchestra rule,
# but with RPL lite routing (non-storing mode).
# We use RPL classic, for which the storing mode is the default.
# According to Orchestra comments and code, the non-storing rule
# can be used with RPL storing mode!

# sender based, storing Orchestra + RPL
FIRMWARE_TYPE_ORCHESTRA_SB=1
# receiver based, storing Orchestra + RPL
FIRMWARE_TYPE_ORCHESTRA_RB_S=2
# receiver based, nonstoring Orchestra, nonstoring RPL
FIRMWARE_TYPE_ORCHESTRA_RB_NS=3
# receiver based, nonstoring Orchestra, storing RPL
FIRMWARE_TYPE_ORCHESTRA_RB_NS_SR=4
# in the future - when implemented
FIRMWARE_TYPE_ALICE=5
# in the future - when implemented
FIRMWARE_TYPE_MSF=6

# Other things that can be turned on or off for the experiments:
# - the burst bit
# - the root rule in the orchestra rules
# - multiple TSCH links per single timeslot (to avoid problems when there are collisions in the Orchestra schedule)
# - whether to add node-based links to alt parents (to enable probing) 
# - "ideal rule" - performance when there's an oracle that tells the nodes when to allocate / deallocate cells. need to think how to implement this (perhaps always listen, but hack the energest module somehow?). or estimate this via the number of empty cells or similarly (e.g. collisions based on logs that include the ASN)

ifndef FIRMWARE_TYPE
  FIRMWARE_TYPE := $(FIRMWARE_TYPE_ORCHESTRA_SB)
endif

ifeq ($(FIRMWARE_TYPE),$(FIRMWARE_TYPE_ORCHESTRA_RB_NS))
  # turn OFF the storing mode
  CFLAGS += -DRPL_CONF_MOP=RPL_MOP_NON_STORING
else
  # by default, turn ON the storing mode
  CFLAGS += -DRPL_CONF_MOP=RPL_MOP_STORING_NO_MULTICAST
endif

CFLAGS += -DFIRMWARE_TYPE=$(FIRMWARE_TYPE)

CFLAGS += -DORCHESTRA_CONF_UNICAST_PERIOD=@ORCHESTRA_CONF_UNICAST_PERIOD@

############################
####### Other config #######
############################

CONTIKI=../../../../../../..

MAKE_MAC = MAKE_MAC_TSCH
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

# Orchestra? (Always enabled)
MAKE_WITH_ORCHESTRA ?= 1
ifeq ($(MAKE_WITH_ORCHESTRA),1)
MODULES += os/services/orchestra
endif

# enable energest (for tests only, not for simulations)
MODULES += os/services/simple-energest

CONTIKI_PROJECT = node
all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
