#
# This exist just for quick cleaning of the subdirectories.
# For the real configuration, see Makefile.common` and `common-conf.h`.
#

all:
	@echo "Recursive make not supported"

clean:
	$(MAKE) -C node clean

distclean:
	$(MAKE) -C node distclean
